### ISSUE TITLE
Outdated Torch versions

### ISSUE THREAD

**Issue by saydemr** [twitter-research/graph-neural-pde#15]
Hello,

Running the GNN on newer GPU's raise the following warning. 

![image](https://user-images.githubusercontent.com/37012364/160480796-d48ec5a8-8106-43cf-b749-56d7081a0d61.png)

Then, after a while the program quits with the following error.

![cuda3070error](https://user-images.githubusercontent.com/37012364/160480674-18685eaa-0340-4f9c-975a-0739e4a4ea27.png)

I understand that these warnings and errors are related with Nvidia and/or PyTorch. However, are there any options that you can update the environment dependencies with newer versions of PyTorch? Maybe newer versions of other packages as well?

Thanks!

**Comment by saydemr** [comment]
Any comments, please?

**Comment by melifluos** [comment]
Have you tried updating your version of Pytorch to one that's compatible with your GPU? You would also need to update the pytorch geometric libraries, but this is now much easier following the release of pytorch geometric v2.0
