### ISSUE TITLE
error

### ISSUE THREAD

**Issue by wkingHacker** [twitter-research/graph-neural-pde#27]
I have installed all dependencies guided by your readme.However, there is a error .Please tell me how to solve it ,thank you.
![QQ_1727008175120](https://github.com/user-attachments/assets/0e7103dc-46ea-49d8-9560-3aa2e42bd7ad)

**Comment by JRowbottomGit** [comment]
Dear wkHacker, pykeops is not a critical dependancy of our project, I would suggest trying to run a subset our code without this library as things have moved on in the years. You may need to comment out some import pykeyops lines. Good luck and best wishes James

**Comment by wkingHacker** [comment]
Thanks for your answer,  I have solved this problem by changing the version of Pytorch.
