### ISSUE TITLE
Minor Errors in Visualise Attention Notebook

### ISSUE THREAD

**Issue by SauravMaheshkar** [twitter-research/graph-neural-pde#3]
First of all great paper and thanks for releasing the code, just a couple of minor fixes in the [**visualise_attention.ipynb**](https://github.com/twitter-research/graph-neural-pde/blob/4323db3bb3badbcfc3c569635b7f8f072946528d/notebooks/visualise_attention.ipynb)

1. Wrong module import at the top of the notebook. **`run_CGNN`** has been used, instead `run_GNN` should be used instead.
2. In the [**data.py**](https://github.com/twitter-research/graph-neural-pde/blob/4323db3bb3badbcfc3c569635b7f8f072946528d/src/data.py) script, the `get_dataset` function requires `opt` to be a `dict`, viz https://github.com/twitter-research/graph-neural-pde/blob/4323db3bb3badbcfc3c569635b7f8f072946528d/src/data.py#L29
but the dataset name has been passed as a `str`. Changing the line to `dataset = dt.get_dataset({'dataset':'Cora', 'rewiring' : None}, '/content/graph-neural-pde/data', use_lcc=True)` for simplicity, or adding a `dataset` key to `opt` would fix the issue.
3. A couple of values are missing in the `opt` such as `use_mlp`, `use_labels`, `fc_out`, `label_rate`,`batch_norm`, `reweight_attention`, `attention_dim`,`label_rate`, `reweight_attention`, `step_size`, `max_nfe`, `no_alpha_sigmoid`, and `add_source`. Maybe change the `opt` to the one from [**test_params.py**](https://github.com/twitter-research/graph-neural-pde/blob/50b970024338c0b23571ccb2776deb156f28531b/test/test_params.py) or adding the aforementioned params would fix the issue. 
4. Maybe add a Colab Notebook. I've been able to successfully reproduce the notebook in this [gist](https://gist.github.com/SauravMaheshkar/bbb2d42facc273f00b918338f121426f), I'd love to open up PR adding a Colab.

**Comment by melifluos** [comment]
@SauravMaheshkar Thanks for finding these and the suggestions for improvement of the repo @JRowbottomGit  is looking into it and please let us know if you find anything else that could be improved.

Best wishes, Ben

**Comment by JRowbottomGit** [comment]
Thanks @SauravMaheshkar those errors were fixed, I've also added run_GNN.ipny.
