### ISSUE TITLE
python run_image.py 

### ISSUE THREAD

**Issue by larbisoft** [twitter-research/graph-neural-pde#6]
Hello
when I run python run_python run_image.py 
I have this error

[pyKeOps]: Warning, cuda was detected, but driver API could not be initialized. Switching to cpu only.
Loading Data
creating in_memory_datasets
creating GNN model
Traceback (most recent call last):
  File "run_image.py", line 349, in <module>
    main(opt)
  File "run_image.py", line 183, in main
    model = GNN_image(opt, batch, opt['num_class'], device).to(device)
  File "/home/boudjelala/Desktop/Tests_code/Abder_GNN/graph-neural-pde/src/GNN_image.py", line 20, in __init__
    super(GNN_image, self).__init__(opt, data, num_classes, device)
TypeError: __init__() takes from 3 to 4 positional arguments but 5 were given

Thanks

**Comment by melifluos** [comment]
Thanks for flagging this @larbisoft, we're taking a look and will get back shortly

**Comment by larbisoft** [comment]
Thank you, I'm still waiting

**Comment by melifluos** [comment]
Hi @larbisoft I've pushed a quick fix. However, may I ask why you're interested in run_image.py? We only used this to generate some figures that illustrate our method and it's certainly not something we plan to support or is properly tested.
