### ISSUE TITLE
20 random initializations and 100 random train-val-test splits 

### ISSUE THREAD

**Issue by alip67** [twitter-research/graph-neural-pde#7]
Hi, 

could you explain how you generate the setting for table 2 in the paper?

 in the paper, you state that " for all datasets using 100 random splits with 20 random initializations." which means that the `set_train_val_test_split` function should generate these splits. could you elaborate on how these parts work in your code?

**Comment by melifluos** [comment]
Yes, I appreciate that this is now very late, but I only just noticed the issue. It happens in ray_tune.py L154. 

In our pipeline we use RayTune to do a hyperparameter search and then we evaluate the best hyperparameters by repeating 100 times with 20 random splits ie. 20 random seeds.
